-- =====================================================
-- Canalblog import - FIXED with proper INSERT statements
-- Generated: 2026-06-09T14:27:54.713Z
-- =====================================================

-- Folders
INSERT OR IGNORE INTO folders (name, slug, icon, sort_order) VALUES ('Maroc', 'maroc', '🇲🇦', 1);
INSERT OR IGNORE INTO folders (name, slug, icon, sort_order) VALUES ('Oman', 'oman', '🇴🇲', 2);
INSERT OR IGNORE INTO folders (name, slug, icon, sort_order) VALUES ('Jordanie', 'jordanie', '🇯🇴', 3);
INSERT OR IGNORE INTO folders (name, slug, icon, sort_order) VALUES ('Égypte', 'egypte', '🇪🇬', 4);
INSERT OR IGNORE INTO folders (name, slug, icon, sort_order) VALUES ('Tunisie', 'tunisie', '🇹🇳', 5);
INSERT OR IGNORE INTO folders (name, slug, icon, sort_order) VALUES ('Espagne', 'espagne', '🇪🇸', 6);
INSERT OR IGNORE INTO folders (name, slug, icon, sort_order) VALUES ('Mauritanie', 'mauritanie', '🇲🇷', 7);

-- Articles
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Octobre 2011', 'maroc-octobre-2011', 'Maroc', '2011-10-07', '2011-10-09', 'Le fameux WE du 07-08-09 Octobre 2011... C''''est là que tout a commencé !!!', 'Le fameux WE du 07-08-09 Octobre 2011... C''''''''est là que tout a commencé !!!', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Mai 2013 – Marrakech', 'maroc-mai-2013-marrakech', 'Maroc', '2013-05-01', '2013-05-14', '** 27 04 2013**', '** 27 04 2013**', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Espagne 2013 – Sierra de Guara', 'espagne-2013-sierra-de-guara', 'Espagne', '2013-07-01', '2013-07-14', '** Vendredi 16 aout**', '** Vendredi 16 aout**', NULL, (SELECT id FROM folders WHERE slug = 'espagne'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Mai 2014 – Fès', 'maroc-mai-2014-fes', 'Maroc', '2014-05-01', '2014-05-14', '27/04/2014 20:05 : décolage de Nantes. Dans 3 heures, nous serons à l''''aéroport de Fès, Maroc, où nous attendra notre voiture de location grand luxe (dacia logan avec clim et GiPièS).', '27/04/2014 20:05 : décolage de Nantes. Dans 3 heures, nous serons à l''''''''aéroport de Fès, Maroc, où nous attendra notre voiture de location grand luxe (dacia logan avec clim et GiPièS).', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Avril 2015', 'maroc-avril-2015', 'Maroc', '2015-04-01', '2015-04-14', 'Cette année,  décollage de Tours. Nous atterrissons à l''''aéroport de Marrakech, Maroc, où nous attendra notre loueur de Dacia et notre GPS. Nous leur avons demandé une voiture avec le plein d''''essence, mais ça n''''est pas dans leur habitude. C''''est simplement plus rassurant pour nous. Une fois les papiers signés et la caution enregistrée, direction Imouzzer, près d''''Agadir, dans la vallée du paradis où nous passerons 3 nuits. Voici le trajet prévu cette année :', 'Cette année,  décollage de Tours. Nous atterrissons à l''''''''aéroport de Marrakech, Maroc, où nous attendra notre loueur de Dacia et notre GPS. Nous leur avons demandé une voiture avec le plein d''''''''ess', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Avril 2016', 'maroc-avril-2016', 'Maroc', '2016-04-01', '2016-04-14', '28/03/2016 : Bonjour à tous, dans 3 jours, nous décollerons de Nantes en direction de Marrakech. Cette année, nous avons élaboré un sympathique petit circuit : Marrakech, Ait Ben Haddou (3 nuits), Ouzoud (3 nuits), Bin el Ouidane (2 nuits) et Fez (2 nuits).', '28/03/2016 : Bonjour à tous, dans 3 jours, nous décollerons de Nantes en direction de Marrakech. Cette année, nous avons élaboré un sympathique petit circuit : Marrakech, Ait Ben Haddou (3 nuits), Ouz', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Octobre 2016', 'maroc-octobre-2016', 'Maroc', '2016-10-07', '2016-10-16', '16/10/2016', '16/10/2016', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Oman Avril 2017', 'oman-avril-2017', 'Oman', '2017-04-01', '2017-04-14', 'Mercredi 15 mars 2017', 'Mercredi 15 mars 2017', NULL, (SELECT id FROM folders WHERE slug = 'oman'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Avril 2018', 'maroc-avril-2018', 'Maroc', '2018-04-01', '2018-04-14', '![](https://storage.canalblog.com/81/04/1250329/120018741_o.jpg)', '![](https://storage.canalblog.com/81/04/1250329/120018741_o.jpg)', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Oman Mars 2019', 'oman-mars-2019', 'Oman', '2019-03-01', '2019-03-14', 'Salam Aleykoum,', 'Salam Aleykoum,', NULL, (SELECT id FROM folders WHERE slug = 'oman'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Octobre 2019', 'maroc-octobre-2019', 'Maroc', '2019-10-01', '2019-10-14', 'Cette année, petite nouveauté, nous partons .... au Maroc  :) :) ', 'Cette année, petite nouveauté, nous partons .... au Maroc  :) :)', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Juillet 2020', 'maroc-juillet-2020', 'Maroc', '2020-07-01', '2020-07-14', 'Certains partent au ski, dans le froid, et bien nous, nous préférons partir au Maroc, dans le chaud  :)', 'Certains partent au ski, dans le froid, et bien nous, nous préférons partir au Maroc, dans le chaud  :)', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc Septembre 2021', 'maroc-septembre-2021', 'Maroc', '2021-09-01', '2021-09-14', 'Bonsoir à tous,', 'Bonsoir à tous,', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Jordanie Avril 2022', 'jordanie-avril-2022', 'Jordanie', '2022-04-29', '2022-05-17', 'A force de voir des reportages sur Petra, nous avons décidé de visiter la Jordanie en Avril 2020.', 'A force de voir des reportages sur Petra, nous avons décidé de visiter la Jordanie en Avril 2020.', NULL, (SELECT id FROM folders WHERE slug = 'jordanie'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc 2022', 'maroc-2022', 'Maroc', '2022-09-18', '2022-10-02', 'Cette année, nous n''''avons pas pris de vacances en Juillet-Aout (clin d''''oeil à nos chers collègues qui nous croient toujours en vacances) 😜 car Trop cher, trop de monde, trop chaud...', 'Cette année, nous n''''''''avons pas pris de vacances en Juillet-Aout (clin d''''''''oeil à nos chers collègues qui nous croient toujours en vacances) 😜 car Trop cher, trop de monde, trop chaud...', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc 2023', 'maroc-2023', 'Maroc', '2023-04-01', '2023-04-14', '27/04/2023 - Les préparatifs', '27/04/2023 - Les préparatifs', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Egypte 2023', 'egypte-2023', 'Egypte', '2023-11-07', '2023-11-25', 'Cette année 2023 a été assez mouvementée. Et en particulier le tremblement de terre au Maroc et l''''attaque du Hamas en Israel.', 'Cette année 2023 a été assez mouvementée. Et en particulier le tremblement de terre au Maroc et l''''''''attaque du Hamas en Israel.', NULL, (SELECT id FROM folders WHERE slug = 'egypte'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc 2024', 'maroc-2024', 'Maroc', '2024-05-01', '2024-05-14', 'Y''''en a marre du froid...', 'Y''''''''en a marre du froid...', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Oman 2024', 'oman-2024', 'Oman', '2024-10-01', '2024-10-14', 'Quand on aime, on y retourne !', 'Quand on aime, on y retourne !', NULL, (SELECT id FROM folders WHERE slug = 'oman'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Oman 2024 – suite', 'oman-2024-suite', 'Oman', '2024-11-01', '2024-11-14', 'Petit crochet par le musée de l''''encens et le site archéologique de Al Baleed, où nous croisons plein d''''oiseaux de long de la rivière et en particulier des ibis falcinelles, pas farouches du tout.', 'Petit crochet par le musée de l''''''''encens et le site archéologique de Al Baleed, où nous croisons plein d''''''''oiseaux de long de la rivière et en particulier des ibis falcinelles, pas farouches du tout', NULL, (SELECT id FROM folders WHERE slug = 'oman'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Tunisie 2025', 'tunisie-2025', 'Tunisie', '2025-04-01', '2025-04-14', 'Petite nouveauté cette année: nous partons au Maghreb !', 'Petite nouveauté cette année: nous partons au Maghreb !', NULL, (SELECT id FROM folders WHERE slug = 'tunisie'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc 2025', 'maroc-2025', 'Maroc', '2025-09-01', '2025-09-14', 'Après une petite escapade en Tunisie, nous reprenons la direction de notre pays de prédilection : Al Maghreb (Le Maroc). Avec au programme : du trek, du canyoning en passant par des endroits magnifiquement connus comme le lac Bin el Ouidane, le ksar Ait Ben Haddou, les cascades d''''Ouzoud et bien sûr Marrakech.', 'Après une petite escapade en Tunisie, nous reprenons la direction de notre pays de prédilection : Al Maghreb (Le Maroc). Avec au programme : du trek, du canyoning en passant par des endroits magnifiqu', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Mauritanie Février 2026', 'mauritanie-fevrier-2026', 'Mauritanie', '2026-02-01', '2026-02-14', 'Cette fois-ci, c''''est une vraie nouveauté. Nous descendons dans le sud ... Et même en dessous du Maroc... Et même en dessous du Sahara Occidental.', 'Cette fois-ci, c''''''''est une vraie nouveauté. Nous descendons dans le sud ... Et même en dessous du Maroc... Et même en dessous du Sahara Occidental.', NULL, (SELECT id FROM folders WHERE slug = 'mauritanie'), 'published');
INSERT INTO articles (title, slug, destination, start_date, end_date, content, short_description, cover_url, folder_id, status) VALUES ('Maroc 2026', 'maroc-2026', 'Maroc', '2026-03-01', '2026-03-14', 'Cette année, nous partons .... au Maroc !', 'Cette année, nous partons .... au Maroc !', NULL, (SELECT id FROM folders WHERE slug = 'maroc'), 'published');