UPDATE articles SET short_description = 'Marrakech, les souks et un tajine partagé à 5 euros : le tout premier voyage qui a donné son nom à notre blog, en mode groupe d''entreprise.' WHERE id=73;
UPDATE articles SET short_description = 'Caution en liquide, essence introuvable et adresse « 15 km route de Targa » : retour à Marrakech pour un road trip semé d''embûches en Dacia.' WHERE id=74;
UPDATE articles SET short_description = 'Direction la Sierra de Guara et ses piscines de village financées par la commune : baignades, chaleur aragonaise et accent à apprivoiser.' WHERE id=75;
UPDATE articles SET short_description = 'Cap sur Fès avec notre Dacia et son GPS, entre chiens errants, hôtel improbable et grande claque de chaleur nord-africaine.' WHERE id=76;
UPDATE articles SET short_description = 'Direction la vallée du paradis près d''Agadir, ancien repaire de hippies, pour un road trip décollé de Tours cette fois-ci.' WHERE id=77;
UPDATE articles SET short_description = 'Avion retardé, col de Tichka en travaux et route de nuit interdite bravée malgré tout : direction Aït Ben Haddou dans le noir total.' WHERE id=78;
UPDATE articles SET short_description = 'Réveil à 3h45 pour filer vers les dunes du sud, la récolte du safran à Taliouine et les gravures rupestres près de Tata.' WHERE id=79;
UPDATE articles SET short_description = 'Cap sur Oman, découvert par hasard sur un stand de voile à la route du Rhum : première escapade en amoureux, sans les enfants.' WHERE id=80;
UPDATE articles SET short_description = '1598 km au programme, bivouac 5 jours sans internet dans le désert et une voisine d''avion inoubliable pour ce vol turbulent vers Marrakech.' WHERE id=81;
UPDATE articles SET short_description = 'Cette fois en mode routards, sans agence : boucle à travers Oman puis cap sur Dubaï et ses buildings, au plus près de la population locale.' WHERE id=82;
UPDATE articles SET short_description = 'Direction M''hamid et les dunes du Sahara pour vivre le festival Taragalte, entre musique du désert et nuits sous les étoiles.' WHERE id=83;
UPDATE articles SET short_description = 'Un Maroc à 40 degrés, entre Marrakech et Tanger, prévu pour l''été... avant qu''un certain covid-19 ne vienne tout annuler.' WHERE id=84;
UPDATE articles SET short_description = 'Genoux fragiles et cheville à peine remise d''une entorse : direction l''ascension du Toubkal, le toit du Maroc à 4167 mètres.' WHERE id=85;
UPDATE articles SET short_description = 'Deux ans d''attente à cause du covid pour enfin découvrir Pétra, le Wadi Rum et la mer Morte : le grand jour est enfin arrivé.' WHERE id=86;
UPDATE articles SET short_description = 'Cap sur le Rif, région rebelle et hispanophone du Maroc, entre ville bleue de Chefchaouen et immenses champs de cannabis.' WHERE id=87;
UPDATE articles SET short_description = 'Sept jours de trek à Taghia avec un guide contacté avant le covid, puis cap sur les dunes de Merzouga par les gorges du Dadès.' WHERE id=88;
UPDATE articles SET short_description = 'Première découverte de l''Égypte qui commence très mal : panne électrique, puis atterrissage d''urgence non expliqué... à Rome !' WHERE id=89;
UPDATE articles SET short_description = 'Treizième voyage au Maroc, entre treks, bivouacs et canyoning : la routine s''installe, mais les galères persistent dès l''arrivée à Agadir.' WHERE id=90;
UPDATE articles SET short_description = 'Troisième séjour à Oman, cette fois pendant 3 semaines complètes, jusqu''à Salalah tout au sud, près de la frontière yéménite.' WHERE id=91;
UPDATE articles SET short_description = 'Suite du grand tour omanais : ibis le long des rivières, encens de Al Baleed et un chicken massala pakistanais qui met le feu aux lèvres.' WHERE id=92;
UPDATE articles SET short_description = 'Changement de cap vers le Maghreb tunisien, sur les traces des décors de Star Wars à Matmata et Tataouine, entre ksours et berbères.' WHERE id=93;
UPDATE articles SET short_description = 'Retour au Maroc pour du trek et du canyoning, avec une boîte à outils suspecte qui intrigue fort la sécurité de l''aéroport d''Agadir.' WHERE id=94;
UPDATE articles SET short_description = 'Grande première en Mauritanie : une semaine de marche dans le désert avec seulement 7 recharges de téléphone et zéro réseau.' WHERE id=95;
UPDATE articles SET short_description = 'Pour la première fois, on part à 4 : Maxime et sa compagne Morgane, les « M&M''s », rejoignent l''aventure marocaine familiale.' WHERE id=96;
